language: objective-c
before_script:
	- ls
  - git submodule update --init --recursive
script: xcodebuild -scheme AtoZAutoBox -configuration Debug test



# compiler:
# - clang
# before_script:
# - npm install webvtt
# - pwd
#
# - sudo apt-get update
# - sudo apt-get install zzuf
# - which zzuf
# - which bash
# - which sh
# script: make check-js
# after_script:
# - cd ./fuzz
# - chmod -R 777 ./fuzzv2.sh
# - ./fuzzv2.sh 0.1
# - cat ./fuzzedFiles/good.tc_1009_missing_line_between_cues.vtt.fuzzed.vtt
# install xcodetest dependencies
# ./install_dependencies.sh
# - brew update
# - brew install xctool
# build via xcodetest
# script: ./build_and_run_unit_tests.sh MyApp MyAppTests
# script: xctool test -project Kiwi.xcodeproj -scheme Kiwi
